widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: true
  -
    name: SURI_PROJECT
    description: 'Project ID or path'
    type: TEXT
    usageExample: '1234'
    required: true
  -
    name: SURI_TYPE_GRAPH
    description: 'Graph type'
    type: COMBO
    defaultValue: 'pie'
    possibleValuesMap:
      - jsKey: pie
        value: Pie
      - jsKey: horizontalBar
        value: Horizontal bar
      - jsKey: bar
        value: Vertical bar
    required: true