widgetParams:
  -
    name: SURI_PROJECT
    description: 'Project ID or path'
    type: TEXT
    usageExample: '1234'
    required: true
  -
    name: SURI_PROJECT_BRANCH
    description: 'Filter on a branch'
    type: TEXT
    usageExample: 'dev'
    required: false
  -
    name: HIDE_TIMETABLE
    description: 'Hide timetable (duration + queued time)'
    type: BOOLEAN
    defaultValue: false
    required: false
  -
    name: SHOW_FAILED_JOBS
    description: 'Show failed jobs'
    type: BOOLEAN
    defaultValue: false
    required: false
